### ISSUE TITLE
Upload/download of categories does not work

### ISSUE THREAD

**Issue by ThomasSchraml** [opencast/annotation-tool#142]
In #113 the upload and download of categories does not work (Firefox and Chrome).

**Comment by JulianKniephoff** [comment]
What does "does not work" mean? :wink:

**Comment by ThomasSchraml** [comment]
Clicking on the download button: I don't get the file with the categories - nothing happens.
Clicking on the upload button: I can't upload a file with categories, because the browser to select the file isn't opened.

**Comment by JulianKniephoff** [comment]
Interestingly enough, contrary to the original title of theis issue, the download and upload features apparently broke independently of one another.

According to `git bisect` the upload button broke in 7b603e3. Looking at this first now.
