### ISSUE TITLE
The category tabs are disconnected from their view in firefox

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#148]
![image](https://user-images.githubusercontent.com/123272/40532228-10dde8e4-5fff-11e8-8967-14d378b217d2.png)

**Comment by ebbertd** [comment]
![Screenshot 2022-03-25 at 13-48-47 Annotating Academic Video](https://user-images.githubusercontent.com/20522234/160123672-611b1fbc-66a3-478d-a993-851e0e8dabe7.png)

Looks fine now.
