### ISSUE TITLE
Annotation-Tool not working with Internet Explorer (LABEL: blocker)

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#160]
Same problem as with Safari: The video is not loading correctly, the video screen hangs in "start loading video" step.

IE-Version: 11.0.9600.19080CO
Updateversionen: 11.0.70

**Comment by JulianKniephoff** [comment]
We decided not to support Internet Explorer anymore. If this is an easy fix or at least a fix that is necessary anyway, to support other browsers (which might actually be the case, considering that we see the same behavior in Safari and Edge), I'm open to PRs, but I (or ELAN in general for that matter won't put any energy into this bug, nor will I introduce IE specific hacks into the code base. On the contrary, I'm looking forward to removing some of them, now that this decision is official. :smile:

NB: Not even Microsoft supports IE anymore; no one should (have to) use it. Microsoft Edge is actually a decent browser, if a Microsoft product is required for some reason, but there are of course even better alternatives. :wink:
