### ISSUE TITLE
Drag and drop of views does not work in Firefox

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#161]
Starting to drag from the view menu already does not work. This is related to #158. The reason is that Firefox does not pass click events down to subelements of a button. This is a known ["bug"](https://bugzilla.mozilla.org/show_bug.cgi?id=843003) but it is also questionable whether having clickable things inside a button.

I guess the question really is: What makes something a `button` semantically? :wink:

**Comment by ebbertd** [comment]
Dragging from the menu in the current master branch and with Firefox works fine.
