### ISSUE TITLE
Documentation: Broken Links

### ISSUE THREAD

**Issue by mliradelc** [opencast/annotation-tool#184]
Hi, I was reading the documentation and I found that the links with the examples of implementation for the player adapter are broken.

https://github.com/opencast/annotation-tool/blob/develop/documentation/Player-adapter-API.md

**Comment by benbro** [comment]
The demo link in the README is also broken:
https://entwinemedia.github.com/annotations/

**Comment by ebbertd** [comment]
The broken links have been removed.
