### ISSUE TITLE
Build currently fails with Opencast versions prior to 7

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#198]
Compiling the tests fails, basically because the `RestServiceTestEnv` moved to it's own module and now lives in a different package.

As a very nasty workaround, you can of course just skip the tests using the `-Dmaven.test.skip` flag, while I figure out how to make the build compatible with both versions at least for some time.

**Comment by JulianKniephoff** [comment]
With Opencast 7 released, I just pushed e58c279, to make the tests work with this version. Now they don't work with 6 anymore, of course, which is still suboptimal.

I also added a note to the installation instructions to disable the tests when building against 6.

Let's see whether we can cone up with a proper solution before 8 gets released and this issue more or less solves itself. :wink:

**Comment by mtneug** [comment]
What kind of incompatibility? Do the failing tests indicate that the annotation tool does not support Opencast 6.x? If not, why are they failing?

**Comment by mtneug** [comment]
Nevermind, I have missed the package update.

**Comment by JulianKniephoff** [comment]
So yeah, @mtneug apparently figured it out, but for the record, let me state it explicitly again:

The ``RestServiceTestEnv` class was moved to it's own module in Opencast 7, namely `opencast-rest-test-environment`, and with that now also lives in a different (java) package.

There is no obvious way to make our test code `import` either the old or the new path, based on the Opencast version we are building against. At least not that I found; if you know anything to the contrary, please let me know! :wink:

**Comment by JulianKniephoff** [comment]
Note also that I forgot something in the original patch; you also need 8f23b98e57ad409a93c8522c2ebaac32d8751df3, to make the tool buildable with Opencast 7 at all (even with `-Dmaven.test.skip`).

**Comment by mliradelc** [comment]
I built for Opencast 7 without issues.

**Comment by JulianKniephoff** [comment]
There, "fixed" it. :stuck_out_tongue_winking_eye:
