### ISSUE TITLE
Add a proper Excel export

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#20]
Originally reported by: **Rüdiger Rolf (Bitbucket: [rrolf](https://bitbucket.org/rrolf), GitHub: [rrolf](https://github.com/rrolf))**

----------------------------------------

Excel might encounter problems in parsing the CSV file. Sven Stauber has a patch to export an XLS already

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/20

**Comment by JulianKniephoff** [comment]
I contacted @staubesv to ask whether he really has some patch already, but I wouldn't get my hopes up too high, considering that I worked on this issue very briefly for SWITCH, too already and there was no preexisting patch invovled. :wink:

**Comment by JulianKniephoff** [comment]
Here is the main part of Sven's answer:

> Ich hatte dazumals MS Excel geöffnet, einige Zeilen eingetippt und mit
> dann das XLSX (XML) angeschaut und es einfach nachgebaut.
> 
> Das ging ziemlich einfach (siehe unten), wobei diese Lösung aktuell
> dazu führt, dass MS Excel mittlerweile erkennt, dass es keine
> "richtige" Excel-Datei ist und eine Warnung ausgibt.
> 
> Allerdings wäre es eine bessere Lösung, eine Java Library dafür zu 
> verwenden.

(Pardon the German, but all stakeholders involved in the decision to remove this from the "Münster-Update" project should be able to understand it. :wink:)

As per our agreement, I'm taking this out of scope, then.

**Comment by dagraf** [comment]
Looks fine, thx!
