### ISSUE TITLE
show/hide free text annotations

### ISSUE THREAD

**Issue by rrolf** [opencast/annotation-tool#201]
Similar to categories free text annotations should be hideable

**Comment by dagraf** [comment]
I totally agree.

**Comment by JulianKniephoff** [comment]
@dagraf maybe I can interest you in reviewing #211? :wink:

**Comment by dagraf** [comment]
@JulianKniephoff yes, it does. thx!

**Comment by JulianKniephoff** [comment]
Closed by #211
