### ISSUE TITLE
Include the annotation tools into iframe

### ISSUE THREAD

**Issue by Lyliian** [opencast/annotation-tool#206]
Hello,

I am trying to include the annotations tools page on Moodle by an iframe but the annotation tool returned an error and stay at "start loading video" : 

TypeError: Argument 1 of Window.getComputedStyle is not an object.

the annotation is working well without iframe.

Someone know how to solve this ? 

Regards,

Lylian.

**Comment by JulianKniephoff** [comment]
Can you get a stack trace for that message/exception?

It might also be useful to see the code for how you are trying to embed the tool.

**Comment by Lyliian** [comment]
Hi,

This is the iframe : 

<iframe allowfullscreen="" src="https://opencast.dsi.uca.fr/annotation-tool/index.html?id=ef554017-2a36-4493-a7da-fede9aa147a2" marginheight="0px" marginwidth="0px" width="1280" height="720" frameborder="0"></iframe>

And there is the trace of that message : 
![image](https://user-images.githubusercontent.com/12525724/55233387-b5932680-5228-11e9-95e6-766c527223ca.png)

Regards,

**Comment by JulianKniephoff** [comment]
@Lyliian can you try whether #208 works for you? It fixed it on my end, at least.

**Comment by Lyliian** [comment]
@JulianKniephoff Woooow ! It's working great.

Thank's a lot !

Best regards,

Lylian.

**Comment by Lyliian** [comment]
@JulianKniephoff It's me again ! We got a problem with the iframe of annotation tool. After put the video in fullscreen and reduce it, the video size changed.

Before : 
![image](https://user-images.githubusercontent.com/12525724/55400436-2a7a9f00-554e-11e9-8cf5-e92246b6915f.png)

After : 
![image](https://user-images.githubusercontent.com/12525724/55400508-61e94b80-554e-11e9-989f-927cc38620ba.png)

It's not appaear when you press escape but just when you press the button for refuce the fullscreen.

**Comment by JulianKniephoff** [comment]
And this happens only when you embed the tool?

**Comment by Lyliian** [comment]
Absolutely !

**Comment by JulianKniephoff** [comment]
I will look into it further when I have some time again. Can you do me a favor and create a new issue for this, and then reference it here?
