### ISSUE TITLE
Enable access for student

### ISSUE THREAD

**Issue by Lyliian** [opencast/annotation-tool#209]
Hello,

i am trying to provide the access to the annotation tool for student but actually they only see "access is denied".
I found in security/mh_default_org.xml that annotation tool is accessible by anonymous. I added the annotate action in the moodle group. 
So do i forget something ? 

Regards,

Lylian.

**Comment by JulianKniephoff** [comment]
Is this "access denied" coming from the annotation tool or is it a generic error page?

If it is the former, the most likely reason is the ACL: To access an event using the annotation tool, the accessing user needs to be granted the `annotate` ACL action on it. See also [here](https://github.com/opencast/annotation-tool/blob/develop/documentation/opencast-installation.md#adding-acl-actions) for necessary setup on the Opencast side of things.

**Comment by Lyliian** [comment]
It's a generic error page, not the annotation tool error message. So the problem isn't the ACL action i think.

**Comment by JulianKniephoff** [comment]
If it's a generic error page then you're right, it's not the ACLs then. And I only just noticed that you already mentioned the ACL action in your OP, so sorry for that. :sweat_smile:

The only other thing coming to mind is allowing access in the `security/mh_default_org.xml` file, which you apparently also already did. :thinking:

Can you provice some more details? For example: What exact URL is the browser requesting when the access denial comes back? Does it work when you access that URL directly, without going through Moodle? I'm poking around in the dark here, so if there is anything else you think might be relevant, feel free to mention it, too.

**Comment by Lyliian** [comment]
Hem there is more details : 

This is the exact url : 
https://opencast.dsi.uca.fr/annotation-tool/index.html?id=17c22683-4b73-4ab8-bb82-d64e6a0de6d9

I can access to it in moodle or outside moodle. But a student cannot, when he try to access that url or in moodle the access denial comes back. 

There is the ACL of the event : 

![image](https://user-images.githubusercontent.com/12525724/55401312-a249c900-5550-11e9-84c2-60a8c9ec59f0.png)

And there is the mh_default_org lines about annotation tool : 

![image](https://user-images.githubusercontent.com/12525724/55401366-cad1c300-5550-11e9-9495-0d8c89c413f7.png)

thank you for helping me ! :D

**Comment by JulianKniephoff** [comment]
> And there is the mh_default_org lines about annotation tool :
> 
> ![image](https://user-images.githubusercontent.com/12525724/55401366-cad1c300-5550-11e9-9495-0d8c89c413f7.png)

Aha, that's the problem! These lines have nothing to do with the Annotation Tool, there is another feature in Opencast having to do with annotations, which these endpoints belong to.

The endpoints you need to allow access to are `/annotation-tool/**` and `/extended-annotations/**`. For the former `method="GET"` should be fine. For the latter I usually just don't specify the `method`, which allows everything, AFAIK.

**Comment by Lyliian** [comment]
Aaaaaaaaaaaaaaaaah It's working THANK YOU :D

**Comment by JulianKniephoff** [comment]
Glad to help! :smile:
