### ISSUE TITLE
Displaying many tracks leads to the timeline controls not being visible

### ISSUE THREAD

**Issue by ebbertd** [opencast/annotation-tool#212]
Displaying many tracks (depending on screen size) leads to the timeline controls no longer being visible. Seems related to #197 

Steps to reproduce:

1. Add more tracks then can be displayed in the current size of the timeline
2. The timeline controls at the bottom are no longer visible

**Comment by dagraf** [comment]
Time controls get still hidden

**Comment by dagraf** [comment]
Is fixed. Thx!
