### ISSUE TITLE
When the zoom gets resetted only the annotations that were visible in the zoomed-in condition are shown

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#221]
Example: I have multiple annotations on the timeline. I then zoom in so only annotations 3-5 are shown. When I then reset the zoom I can see the whole timeline but only the annotations 3-5. All other annotations do not appear in the timeline.

**Comment by JulianKniephoff** [comment]
This should also be fixed now.

**Comment by dagraf** [comment]
Yep. Thx!
