### ISSUE TITLE
When the annotation tool is deployed, changes the number version of opencast

### ISSUE THREAD

**Issue by mliradelc** [opencast/annotation-tool#237]
Hi,

After deploying the annotation tool in Opencast, the admin UI gets the Opencast version number of the annotation tool instead of the number version of Opencast.
![Screenshot 2019-07-03 at 14 15 20](https://user-images.githubusercontent.com/8040628/60591121-0a9d8600-9d9e-11e9-85c9-dc0ab39a2e20.png)

**Comment by JulianKniephoff** [comment]
Ha, that's funny! :smile: 

That version string is somehow generated by looking at all bundles with the prefix `opencast-`, which our bundles also use. We should probably just rename them; the naming in this project is all over the place, anyway. x)

But it would be nice to bring in some more consistency, while we are at it. Ticket follows.

**Comment by JulianKniephoff** [comment]
Is this still an issue with the new bundle naming scheme introduced in f9079af?

**Comment by mliradelc** [comment]
> Is this still an issue with the new bundle naming scheme introduced in [f9079af](https://github.com/opencast/annotation-tool/commit/f9079af799a981a7205fd10712258fc5a7def51b)?

Yep, the problem with the naming is the children pom, they don't get the root name of annotation tool when they are built.

Y solved the naming renaming que children bundles (and the karaf bundle properties) but still I can't solve the versioning issue.

**Comment by JulianKniephoff** [comment]
Not sure I understand what you mean. To be clear: What I mean is: Is the versioning issue, i.e. Annotate overriding the displayed Openast version, solved with the new project/bundle names introduced in f9079af?

Or does that introduce other issues? If so, please make dedicated issues for that, as stated in #246.

Because if you just change back the names to have the `opencast-`-prefix, of course this issue is going to persist. That build number is generated by looking at all bundles with an `opencast-`-prefix. :wink:

**Comment by mliradelc** [comment]
Ok lets be more clear about this,

There are actually two issues:

- The naming (#246)
- The Versioning (This Ticket)


---------------

> Not sure I understand what you mean. To be clear: What I mean is: Is the versioning issue, i.e. Annotate overriding the displayed Openast version, solved with the new project/bundle names introduced in [f9079af](https://github.com/opencast/annotation-tool/commit/f9079af799a981a7205fd10712258fc5a7def51b)?

There is stil the issue 😭 

If you build as always:

`mvn clean install -DdeployTo=<opencast-dir> -Dopencast.version=<your Opencast version number>`

You find that the files are named `<name>-0-SNAPSHOT` when you deploy that, opencast take the version of the annotation tool (Whatever version name had) instead to keep their version number. 

----------------

[f9079af](https://github.com/opencast/annotation-tool/commit/f9079af799a981a7205fd10712258fc5a7def51b) introduced that the jars are not identificable anymore when you build that.

The naming issue was closed and to this ticket. I solved this issue renaming the artifactsID of each subproject and the Karaf Feature POMs files but I haven't made the PR until be clear about how we have to call without making other issue.

**Comment by JulianKniephoff** [comment]
Okay I tested this just now and I can't reproduce it.

I have the Annotation Tool bundles with their new name and version scheme (current `master`) installed; the Karaf console lists them as

```
363 │ Active   │  80 │ 0.0.0.SNAPSHOT          │ frontend
364 │ Active   │  80 │ 0.0.0.SNAPSHOT          │ Opencast Annotation Tool :: Backend :: API
365 │ Active   │  80 │ 0.0.0.SNAPSHOT          │ Opencast Annotation Tool :: Backend :: Frontend D
366 │ Active   │  80 │ 0.0.0.SNAPSHOT          │ Opencast Annotation Tool :: Backend :: Implementa
```

But Opencast correctly shows its version in the Admin-UI:

```
Opencast 7.0.0.SNAPSHOT - 389a191
```

**Comment by JulianKniephoff** [comment]
Since I can't reproduce this (anymore), I'm assuming this is fixed. If you, @mliradelc, or anyone else thinks it is not, feel free to reopen it with more detailed instructions. :smile:
