### ISSUE TITLE
Naming in Opencast in bundle output files after compile

### ISSUE THREAD

**Issue by mliradelc** [opencast/annotation-tool#246]
Hi, 

One of the things I notice about is that after the fix in [f9079af](https://github.com/opencast/annotation-tool/commit/f9079af799a981a7205fd10712258fc5a7def51b) the files don't have the name of "annotation-tool" for identifying. Also, the version number in the file doesn't appear anymore, it is only number zero.

Actual result:

- api-0-SNAPSHOT.jar
- frontend-0-SNAPSHOT.jar
- frontend-delivery-0-SNAPSHOT.jar
- impl-0-SNAPSHOT.jar

Expected result:

- annotation-tool-api-3-SNAPSHOT.jar
- annotation-tool-frontend-3-SNAPSHOT.jar
- annotation-tool-frontend-delivery-3-SNAPSHOT.jar
- annotation-tool-impl-3-SNAPSHOT.jar

**Comment by mliradelc** [comment]
Ok, I think that I resolved the naming of the jar files, except the thing with the version number because it overwrites the Opencast Version, so still is attached this to #237.

**Comment by JulianKniephoff** [comment]
This is actually intended. See 6897c7c and f9079af. The latter should actually **fix** #237. This was done as part of my efforts to put some CI in place, and simultaniously think about the formalities of the development and release process of this project.

I will write up the exact changes and their motivation in the near future, and post it somewhere prominent for all involved parties to see.

That means I'm going to close this issue. If there is any specific problem with the new naming, feel free to open a new one specifically about that. :smile:
