### ISSUE TITLE
Once deleted annotations show up after hiding and showing again

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#249]
When I delete an annotation, then hide this annotation-type (e.g. this category or free text annotations) using the eye-icon and then "show" them again, the once deleted annotations show up in the list. They do not show up in the timeline.

**Comment by dagraf** [comment]
Does work most of the time, but not always. Have not found any rule. See screencast.
[Deleted annotations show up again.mp4.zip](https://github.com/opencast/annotation-tool/files/4292575/Deleted.annotations.show.up.again.mp4.zip)

**Comment by dagraf** [comment]
Bug still exists. I guess I found a rule:
- When I delete two annotations in a row the second annotation i deleted shows up again. For example: I delete annotation "1", then directly "2" and then hide and show free text annotations, annotation "2" gets shown again.
- When I try to delete three annotations in a row the modal "Delete annotation" does not close itself when I click on delete. When I then click "Abbrechen" the modal does close. Result: This third annotation "3" is still shown in the list but not on the track. When reloading the page the annotation "3" does also disappear from the list.

For me it seems something goes wrong when two annotations get deleted in a row.

**Comment by dagraf** [comment]
Bug still exists. I guess I found a rule:
- When I delete two annotations in a row the second annotation i deleted shows up again. For example: I delete annotation "1", then directly "2" and then hide and show free text annotations, annotation "2" gets shown again.
- When I try to delete three annotations in a row the modal "Delete annotation" does not close itself when I click on delete. When I then click "Abbrechen" the modal does close. Result: This third annotation "3" is still shown in the list but not on the track. When reloading the page the annotation "3" does also disappear from the list.

For me it seems something goes wrong when two annotations get deleted in a row.

**Comment by dagraf** [comment]
Bug does also appear when I insert e new annotation between deleting annotation 1 and 2.

**Comment by ebbertd** [comment]
@dagraf Can you still reproduce this? I can not.

**Comment by dagraf** [comment]
No, I can't. Bug seems to be fixed. Therefore I close this issue.
