### ISSUE TITLE
Fatal Error! You are not allowed to annotate this video!

### ISSUE THREAD

**Issue by fishfree** [opencast/annotation-tool#252]
I followed the wiki to install the annotation-tool in my Opencast 7.2 all-in-one. But when I open a page:  https://******/annotation-tool/index.html?id=62ccc2be-7306-45fe-91c1-c468459e8762. It shows: Fatal Error! You are not allowed to annotate this video!
I already logged in as the admin(ROLE_ADMIN) user.

**Comment by JulianKniephoff** [comment]
Normally this means that there is something wrong with the ACLs. Does `ROLE_ADMIN` have the action `annotate` on the video?

**Comment by fishfree** [comment]
@JulianKniephoff  I see. Thank you for your tips!
