### ISSUE TITLE
No "Annotation tool" can be selected on the Processing step of the Create event page.

### ISSUE THREAD

**Issue by fishfree** [opencast/annotation-tool#253]
I followed the [installation instructions](https://github.com/opencast/annotation-tool/blob/master/documentation/opencast-installation.md) to install this tools for my opencast-7-allinone instance, and add the annotation configuration in the /etc/opencast/workflows/fast.xml just after the publish-engage operation:
```
<operation
  id="publish-configure"
  exception-handler-workflow="partial-error"
  description="Publish to preview publication channel">
  <configurations>
    <configuration key="source-tags">preview</configuration>
    <configuration key="channel-id">annotation</configuration>
    <configuration key="url-pattern">http://localhost:8080/annotation-tool/index.html?id=${event_id}</configuration>
  </configurations>
</operation>
```
And I systemctl restart opencast. Then manually add an event, at the processing step, there is still no "Annotation tool" can be selected, just as the screenshot below:
![noannotationoption](https://user-images.githubusercontent.com/1741341/64472023-f8b7d500-d18a-11e9-9ce8-6438f3d1c459.png)

I still finished the event creation, and after Opencast successfully finished processing the event,  Then I tried to forcely open the annotation tool of the event. The page stuck as the screenshot below:
![annotationstuck](https://user-images.githubusercontent.com/1741341/64472080-8267a280-d18b-11e9-93fd-93c30c7decd9.png)

My version: Opencast 7.2.0 - 8bb9948
BTW:  the publication.channel config file for 7.2 is listproviers/publication.channels.properties. The config format is a little different. I appended the annotation tool the way as others:
```
api={"label":"EVENTS.EVENTS.DETAILS.PUBLICATIONS.EXTERNAL_API", "order":1}
oaipmh-default={"label":"Default OAI-PMH Repository", "order":2}
engage-player={"icon":"img/engage_2x.png", "order":3}
youtube={"icon":"img/youtube_2x.png", "order":4}
engage-player={"icon":"img/engage_2x.png", "order":5}
annotation={"label":"Annotation Tool", "order":6}

```

**Comment by JulianKniephoff** [comment]
The fact that there is no option for the Annotation Tool in the configuration panel is totally expected, from what you told me. It does not appear by you just adding the `publish-configure`-option. If you want something like that, you can add the corresponding HTML to the `configuration_panel` tag of your workflow. See [here](https://docs.opencast.org/develop/admin/configuration/workflow/) for more details on that.

Next, the console output you posted shows a `500` error code. That's a server error. Do you see anything interesting in the Opencast logs?

**Comment by fishfree** [comment]
@JulianKniephoff Now I truncate /var/log/opencast/opencast.log  file and run systemctl restart opencast. The page shows no 500 error but a few 404 errors as the screenshot below:
![annotationerror2](https://user-images.githubusercontent.com/1741341/64583039-29ce1a80-d3c2-11e9-8764-03f956268ba8.png)

I then check there is nothing yet in my /var/log/opencast/opencast.log  file

**Comment by JulianKniephoff** [comment]
That particular error message occurs when the tool can't get the media package from Opencast's search service. Did you publish your event to Engage? Or does your user not have read permissions on it?

**Comment by fishfree** [comment]
@JulianKniephoff Thank you for your tip. Now I insteadly use the "Process upon upload and schedule" workflow ( I added annotation operation config in the schedule-and-upload.xml), and checked publishToEngage, and granted "manage annotations" & "annotate" permissions to all roles. Now, I can see the annotation tool as the screenshot below:
![ss1](https://user-images.githubusercontent.com/1741341/64684094-0fc23400-d4b7-11e9-936f-d93863791452.png)
When I click the green play button, the stucking page shows again as below:
![ss2](https://user-images.githubusercontent.com/1741341/64684265-5fa0fb00-d4b7-11e9-901f-2320b27d88cc.png)
The 2 404 errors can be neglected, it's due to lack of interface translation files. But when I right click the 500 error link (that is /extended-annotations/users) and open in the new tab, it shows up 404.

I deploy a Nginx as the reverse proxy, so I replace the localhost:8080 with the nginx server name in the section of annotation in the workflow XML file. If I don't replace, the annotation page will go to localhost:8080/****, which is not accessible.

**Comment by JulianKniephoff** [comment]
Is there anything in the Opencast logs? A status code of `500` indicates a server-side error.

**Comment by fishfree** [comment]
@JulianKniephoff There is nothing in the /var/log/opencast/opencast.log nor in /var/log/nginx/error.log, for I use Nginx reverse proxy.

**Comment by JulianKniephoff** [comment]
I'm not sure why this would lead to a `500` (I would expect a `403`), but another common trap is to not enable access to the annotation tool APIs in the `security/mh_default_org.xml` file (or the corresponding file of your organization, should you run a multi tenant setup). At least `ROLE_USER` needs to be able to at least `GET`, `POST`, `PUT` and `DELETE` stuff under `/extended-annotations`.

If that doesn't help, it could be useful to see the full request and response. You should be able to get that from the "Network" tab of your development tools in the browser.

**Comment by fishfree** [comment]
@JulianKniephoff I don't use multi tenant setup. There is no 

> /extended-annotations

 settings in my 

> security/mh_default_org.xml 

 file. So I added these 4 lines under the /annotation section:
```
    <!-- Enable anonymous access to the annotation and the series endpoints -->
    <sec:intercept-url pattern="/series/**" method="GET" access="ROLE_ANONYMOUS, ROLE_CAPTURE_AGENT" />
    <sec:intercept-url pattern="/annotation/**" method="GET" access="ROLE_ANONYMOUS" />
    <sec:intercept-url pattern="/annotation/**" method="PUT" access="ROLE_ANONYMOUS" />
    <sec:intercept-url pattern="/extended-annotations/**" method="PUT" access="ROLE_ADMIN, ROLE_USER, ROLE_ANONYMOUS" />
    <sec:intercept-url pattern="/extended-annotations/**" method="GET" access="ROLE_ADMIN, ROLE_USER, ROLE_ANONYMOUS" />
    <sec:intercept-url pattern="/extended-annotations/**" method="POST" access="ROLE_ADMIN, ROLE_USER, ROLE_ANONYMOUS" /> 
    <sec:intercept-url pattern="/extended-annotations/**" method="DELETE" access="ROLE_ADMIN, ROLE_USER, ROLE_ANONYMOUS" />
```
Is it right? After systemctl restart opencast, the error still exists.

**Comment by fishfree** [comment]
@JulianKniephoff I followed your instruction, under the tab of Network, it's a xhr 500 error,
![network](https://user-images.githubusercontent.com/1741341/65410194-4c2d5280-de1c-11e9-9b2c-77541b10fa2e.png)

and furtherly in the tab of Sources, the error occured on this line: xhr.send( ( s.hasContent && s.data ) || null );
![sources](https://user-images.githubusercontent.com/1741341/65410208-57807e00-de1c-11e9-9720-b14c841a8357.png)

**Comment by JulianKniephoff** [comment]
Could you check whether the Annotation Tool `-impl` bundle is actually running in your Karaf container? And maybe restart it?

**Comment by JulianKniephoff** [comment]
Also: I would like to keep the issue tracker somewhat clean. We are far away from the original issue now. Could you please create a new one if this is still a problem for you?

**Comment by fishfree** [comment]
@JulianKniephoff Could you pls tell me how to checkAnnotation Tool -impl bundle is actually running in my Karaf container? I googled nothing relevant.

**Comment by JulianKniephoff** [comment]
In the Karaf console you can type `bundle:list`. It should show up in the resulting list.

**Comment by uday5650** [comment]
I have tried to install opencast 9.9, getting 

URI: | /
-- | --
404
Not Found
org.ops4j.pax.web.service.spi.model.ServletModel-445

Can anyone help me 
<img width="921" alt="Error 404" src="https://user-images.githubusercontent.com/47739638/141774153-1583ded1-001c-4823-a915-0755860a73f1.PNG">

**Comment by JulianKniephoff** [comment]
@uday5650 this is really not the place for general Opencast installation support. You might want to check any of [these channels](https://docs.opencast.org/#communication-help) for that.
