### ISSUE TITLE
Timeline not shown in Safari

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#288]
When opening the annotation tool with Safari the timeline is missing (see screenshot).
<img width="1271" alt="Bildschirmfoto 2019-12-18 um 11 59 51" src="https://user-images.githubusercontent.com/15246287/71080677-eb4cb680-218d-11ea-8090-3c1de453984d.png">

**Comment by JulianKniephoff** [comment]
I can reproduce this in Epiphany. This seems to be a WebKit-related problem. I'm on it.

**Comment by dagraf** [comment]
Works as expected on SWITcast-Test.
