### ISSUE TITLE
Cursor does not change back to arrow when a annotation gets moved on the timeline

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#289]
See screencast: When I activate an annotation and then move it on the the timeline the cursor gets shown as a cross. After having moved the annotation the cursor remains in this cross-shape. When I do such a "moving-an-annotation-movement" next to an annotation (click > move the mouse while having "pushed" the mouse button > release the button) the cursor returns to its arrow-shape.

[Annotation Tool_Cursor ändert sich und bleibt so.mp4.zip](https://github.com/opencast/annotation-tool/files/3978140/Annotation.Tool_Cursor.andert.sich.und.bleibt.so.mp4.zip)

**Comment by luniki** [comment]
Done in 8cadb4eb305b279068fd2b5c72c228ed6e824238
