### ISSUE TITLE
Shared tracks should be in read-only mode

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#293]
When I open a track of somebody else that is public or shared with administrator I can select this track and alter it. This should not be possible. In the old version of the tool I can not select tracks of others.

What I can do:

- Double clicking on the track opens the window "Edit track" where I can edit name, description and access. Hint: This bug exists also in the old version of the tool.
- I can add own annotations to this foreign track.
- Using the options on the timeline I can move and alter the duration (start/ending) of annotations. These changes do not get saved, though.

**Comment by dagraf** [comment]
I can still us the options on the timeline (move and alter the duration (start/ending) of foreign annotations). Now the changes get also saved and become visible in the list of annotations.

**Comment by JulianKniephoff** [comment]
@dagraf that's probably because I didn't deploy the PR yet, for some reason. :see_no_evil: 

I will do that now. :sweat_smile:

**Comment by JulianKniephoff** [comment]
Actually no, that was a real oversight in the code. I'm on it.

**Comment by dagraf** [comment]
Works as expected on SWITCHcast-Test.

**Comment by dagraf** [comment]
Works as expected on SWITCHcast.
