### ISSUE TITLE
Newly inserted annotations can not be seen

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#299]
As newly inserted annotations have no length any more they can not be seen because they get totally hidden by the red line representing the playhead.

Solution:

- The minimum width of point of time annotations is as wide as the letter "W". So all newly inserted annotations are this wide.
- To differentiate between point of time annotation and time duration annotation: Point of time annotations have an anchorage to the time bar, time durations have not.
- This anchorage has the same color as the boarder of its annotation and starts not in the middle but slightly to the left.
<img width="434" alt="Bildschirmfoto 2019-12-18 um 16 44 29" src="https://user-images.githubusercontent.com/15246287/71100675-b6545a00-21b5-11ea-904f-c4d52c7b7e20.png">

**Comment by dagraf** [comment]
@ebbertd As I've heard that this was your request that point in time annotations have no length at all: What do you think about my suggestion?

With Julian I also discussed the possibility to use e triangle or another shape for point in time annotations. In my opinion the downside with a triangle is, that I can not drag the start and end of a point in time annotation to convert it into a time duration annotation.

**Comment by ebbertd** [comment]
@dagraf I like your solution. You are right that using a triangle or another shape would result in the described problem.

**Comment by JulianKniephoff** [comment]
@dagraf if I understand you correctly, dragging the annotation would still give it a duration and thus make it a "range annotation." But what happens if the user then makes the annotation shorter than the width of "W"? What if they make the duration 0?

**Comment by dagraf** [comment]
@JulianKniephoff 
- When shorter than the width of W: It remains a "range annotation" (without anchorage) and is shown shorter in its exact length (which could be shorter than the width of W)
- When I make the duration 0: It becomes a point of time annotation with an anchorage and with the above indicated minimum length of newly inserted annotations.

**Comment by JulianKniephoff** [comment]
Unfortunately the timeline does not let us resize these anchored items. We would have to first convert them back to range items. This would make the process of changing the duration of a point-in-time annotation a two-step flow:

1. First we need to give it some arbitrary duration by some user interaction,
2. then we can drag at the range's ends.

Questions are of course:

* What user interaction should do the conversion
* What should the arbitrary duration be?
** What should (and can) that depend on?

Note that there are actually already two interactions that do something like this, but they might not be sufficient:

* You can select an annotation, then navigate to somewhere else in the video, and press the `.` key. This sets the end of the currently selected annotation to the point in the video that is currently playing.
* Similarly, you can enable edit mode for the annotation in the list view, navigate to somewhere in the video and press the `OUT`-button.

Thoughts?

**Comment by dagraf** [comment]
That's really a shame... grmpf... Here my first thoughts:
- Because anchored times (and to say point-in-time annotations) can not be resized by dragging the ends we could return to the idea of a triangle to indicate them on the timeline.
- User interaction to do the conversion: Double click on an annotation on the timeline activates the edit option (see https://github.com/opencast/annotation-tool/projects/2#card-24353980). Users then have to navigate the video and press the IN or OUT Button.
- Ergo: I would not change it to some arbitrary duration.

This brings me to other questions:
- How can I change a range item/duration annotation to a point-in-time annotation?
- At the moment I can alter the length of a newly inserted annotation by dragging on the (not visible) ends. How is this possible? Are newly inserted annotations saved with a duration?

**Comment by JulianKniephoff** [comment]
Every annotation has a duration. The distinction between range and point in time is a matter of interpretation: The list view does not display the end-time if the duration is exactly 0. The timeline, too, could check this and display annotations differently.

Once #315 is merged, you can do the "conversion" using the drag & drop interface. You could theoretically do it in the list view as well, by setting the end time to exactly the start time. This is awkward at the moment, though, since the display and the editing text box for the times display a less accurate representation of the times. So if the list view shows the start to be `0:10` and the end to be `0:11`, that `0:10` could actually be `0:10:15` and then setting the end to exactly `0:10` will give you an error. But there is no way to set it to exactly `0:10:15`! See also #308.

**Comment by dagraf** [comment]
What do you mean with "drag & drop interface"? Means this by dragging the end? Or anything else?f

After discussing the option with the triangles with a team mate we like to discharge this option definitely. We suggest to stick with only boxes.

**Comment by JulianKniephoff** [comment]
Yes, I meant dragging the ends, sorry for the confusion. :sweat_smile: 

Okay, so boxes for everything, but pont-in-time annotations have an anchor, yes? And to convert, you have to go through the list view, or we can of course always try to think about better interactions. Roger?

**Comment by dagraf** [comment]
Yes to everything. But if there is some solution to get rid of this detour to convert point-in-time annotations with anchor in duration annotations, this would be great.

Some specifications:
- Anchors run in the "background". They are covered by (i) existing annotations and (ii) by whole other tracks if their own track is not activated. 
- If their own track is activated, anchors disappear only behind existing annotations.
- Anchors of an active annotation run in the "foreground" and do not disappear at all.
- Anchors of activated annotations get also highlighted (similar to how active annotations get highlighted).
- Add some space between stacked annotations and between the top and bottom annotations and the boarder of their tracks. So that for example an anchor behind two stacked annotationscan be seen (see example above).
- General: Make boxes slightly smaller (maximum hight see hight of annotations in list view) and take care that the written text in the boxes gets centered (see example above).

**Comment by dagraf** [comment]
Maybe a stupid question: To convert a point-in-time annotation with anchor to a duration-annotation without anchor I have to through the list view. But the conversion the other way around (duration-annotation without anchor > point-in-time annotation with anchor) can be done be dragging the end (start) of an annotation to its start (end), right?

**Comment by JulianKniephoff** [comment]
> Maybe a stupid question: To convert a point-in-time annotation with anchor to a duration-annotation without anchor I have to through the list view. But the conversion the other way around (duration-annotation without anchor > point-in-time annotation with anchor) can be done be dragging the end (start) of an annotation to its start (end), right?

Yes. I know it's suboptimal, but that's how it is/will be for the moment. :disappointed:

**Comment by JulianKniephoff** [comment]
> Yes to everything. But if there is some solution to get rid of this detour to convert point-in-time annotations with anchor in duration annotations, this would be great.

Great. I created #323 to track ideas and further discussion about simplifying the problematic conversion.

> Some specifications:
> [...]

I will see which ones of these I can (easily) implement.

**Comment by JulianKniephoff** [comment]
One weakness of this design is that point-in-time annotations that are near the end or the start of the video get cut off on the left or right ... Thoughts?

**Comment by dagraf** [comment]
Best solution: Anchors are always accurately situated. When an annotation is near the end (start) of the video the annotation ends (starts) at the end (start) of the video. With such annotations the anchor is not centered but moved to the right (left) of the annotation.

Other solutions in order of priority:
- The above mentioned solution works for the start but not for the end.
- Anchors are situated always at the very beginning of an annotation and we solve the "end-problem" (see description above).
- Anchors are situated always at the very beginning of an annotation and we live with the "end-problem". 
- We live with this.

**Comment by JulianKniephoff** [comment]
I think unfortunately the answer has to be "we live with this", at least for now. I created #326 to track any further work on this particular problem, but it is harder than expected and we won't solve it for the hotfix release for sure.

**Comment by JulianKniephoff** [comment]
I will look at getting the lines to behave like @dagraf wants. Here are the specs again as a checklist, for my own convenience. :P

> Some specifications:
> - [ ] Anchors run in the "background". They are covered by (i) existing annotations and (ii) by whole other tracks if their own track is not activated. 
> - [ ] If their own track is activated, anchors disappear only behind existing annotations.
> - [ ] Anchors of an active annotation run in the "foreground" and do not disappear at all.
> - [ ] Anchors of activated annotations get also highlighted (similar to how active annotations get highlighted).
> - [ ] Add some space between stacked annotations and between the top and bottom annotations and the boarder of their tracks. So that for example an anchor behind two stacked annotationscan be seen (see example above).
> - [ ] General: Make boxes slightly smaller (maximum hight see hight of annotations in list view) and take care that the written text in the boxes gets centered (see example above).

**Comment by JulianKniephoff** [comment]
Implementing this, I'm not too sure whether I like the first two points on the checklist. But let's talk about this once it is deployed and people had a chance to look at it.

**Comment by dagraf** [comment]
Some thoughts after first tests:
- I expected the anchors of category annotations to have the same colour as the annotations (see examples above).
- The momentary solution with lines now also disappearing behind the track they originate from, if that track is not selected, I do not like at all. Lets discuss in the next meeting why this is doable but "not nice".
- I would like to have a bit more space between the timeline and the uppermost annotations so as the anchor can be seen (and not only a dot).
- Make boxes of annotations slightly smaller.

**Comment by dagraf** [comment]
Some additional thoughts:
- Make point-in-time annotation slightly less wide (around two-thirds of the momentary range).

**Comment by JulianKniephoff** [comment]
Notes from the last VC:

* Anchors get 3 visibility "levels":
  * Anchors of selected annotations will be **very** visible
  * Anchors of annotations in the selected track will be noticable
  * Everything else will just be very faintly visible
* Anchors should have the same hue as the annotation
