### ISSUE TITLE
Shortening a time duration annotation to a point of time annotation does not work

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#300]
Trying to shorten a time duration annotation to a point of time annotation by dragging the end/beginning of the annotation in the timeline does not work. On the timeline the annotation appears as a point in time annotation but in the list of annotation the annotation has still the old start- and end-time indicated.

When pulling the start of an annotation to the end this start can be pulled further than the actual end of the annotation which ends in an point in time annotation with a time that is later in time that the initial end of this annotation. In the list of annotation this annotation is still indicated as time duration annotation with the initial start and end time.

**Comment by dagraf** [comment]
Works as expected on SWITcast-Test.

**Comment by dagraf** [comment]
Works almost as expected on SWITCHcast. Why almost: I expected the point-in-time annotation to appear with a anchor. See you answer here: https://github.com/opencast/annotation-tool/issues/299#issuecomment-580149602

**Comment by JulianKniephoff** [comment]
I will look into it.

**Comment by JulianKniephoff** [comment]
Okay I can reproduce this. In fact "converting" an annotation like this does not even seem to be persisted.

**Comment by dagraf** [comment]
Looks fine on SWITCHcast-Staging. Thx!
