### ISSUE TITLE
When dragging the playhead over the end of the timeline it jumps back to the beginning of the video

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#303]
Expected behavior: It should stay at the end of the video.

**Comment by luniki** [comment]
The problem stems this function https://github.com/opencast/annotation-tool/blob/a5e4bcb28b12273c67a3dff955bec81dc0eb92bd/frontend/js/views/timeline.js#L439

When the custom time marker is dragged farther than the duration of the video, this results in setting the playhead of the video to that duration.

The video player realizes that the video is at its end and switches directly to the beginning.

Now the custom time marker gets reset to the new position of the playhead.

**Comment by luniki** [comment]
I  propose as a solution in line https://github.com/opencast/annotation-tool/blob/a5e4bcb28b12273c67a3dff955bec81dc0eb92bd/frontend/js/views/timeline.js#L443 to subtract a small enough delta from the duration of the video. I tried 0.01 and this worked as expected.

**Comment by luniki** [comment]
This is better solved via #350

**Comment by JulianKniephoff** [comment]
#350 is not merged, yet, so this should stay open for now.

**Comment by dagraf** [comment]
Looks fine on SWITCHcast-Staging. Thx!
