### ISSUE TITLE
Annotations shorter than 5 sec are to long indicated as active

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#317]
Point-in-time annotations and duration annotations shorter than 5 seconds are displayed as active for 5 seconds (see https://tube.switch.ch/videos/becff00e).

Desired behavior: 
- Point-in-time annotations: Indicated as active for 1 second
- Duration annotations: Active only as long as the actual duration of the annotation

**Comment by dagraf** [comment]
Moved to "next"

**Comment by luniki** [comment]
This seems to be intended. There is a configuration option MINIMAL_DURATION which has a value of 5:
https://github.com/opencast/annotation-tool/blob/b62a17f8db52f7fc12a06cce56d7e3270547c6bc/frontend/build/profiles/local/annotation-tool-configuration.js#L59

This is used to select all active annotations:

https://github.com/opencast/annotation-tool/blob/b62a17f8db52f7fc12a06cce56d7e3270547c6bc/frontend/js/annotation-tool.js#L470

The implementation of `annotation.covers`: 
https://github.com/opencast/annotation-tool/blob/b62a17f8db52f7fc12a06cce56d7e3270547c6bc/frontend/js/models/annotation.js#L243

could certainly be changed to accept different configuration options: one for "point-in-time" and one for "duration" annotations.

What do you think about this, @JulianKniephoff ?

**Comment by dagraf** [comment]
Looks fine on SWITCHcast-Staging. Thx!
