### ISSUE TITLE
Single click selects annotation, double-click jumps to it

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#331]
When I have freshly selected a time-in-point annotation (that has now an anchor) and I want to move this annotation I have to almost click on the edge of the annotation to be able to do so. Otherwise I move the playhead. This is because the red line of the playhead "takes to much space" in the sense of when clicking slightly right or left of the playhead I still move the playhead and not the annotation below.

Solution: Make this space much smaller (at least half as wide as now).

**Comment by JulianKniephoff** [comment]
I am not sure I agree once more, sorry. :sweat_smile: 

As someone with rather impaired vision, I dislike tiny UI elements with no leeway to click/drag them with a passion. The real problem in my opinion is that clicking on an annotation currently unconditionally moves the play head to that position. Now I'm not a user of the tool of course, but at least for me that is almost **never** the intention. Can you confirm this?

Maybe we can decomplect the interactions of "moving the play head" and "clicking annotations." somehow. We might even think about lifting the restriction of having to select an annotation to move/resize it in the first place. :thinking:

**Comment by JulianKniephoff** [comment]
Related: #287.

**Comment by dagraf** [comment]
Again (see https://github.com/opencast/annotation-tool/issues/287#issuecomment-577672612): The moving of the play head to the position of an annotation when clicking on it is a central feature of the annotation tool.

A different solution would be to differentiate between single and double click. Single click = annotation gets selected but play head does not get moved. Double click = annotation gets selected and play head jumps to the beginning of an annotation and activates the edit option (see:  https://github.com/opencast/annotation-tool/issues/321#issue-556224721).

**Comment by dagraf** [comment]
looks fine. thx!
