### ISSUE TITLE
Omit eye icon for "access" settings, becaus we us the eye icon differently now (hide annotations). Idea:

### ISSUE THREAD

**Issue by luniki** [opencast/annotation-tool#341]
Public = Globe
Private = Lock or person-icon

**Comment by luniki** [comment]
Are these the icons you mean @dagraf ?
![Selection_035](https://user-images.githubusercontent.com/2993/75224886-b1a9b480-57a9-11ea-84f0-8b4c1db04980.png)

**Comment by dagraf** [comment]
Yes. Please get also rid of the eye-icon next to "reset zoom".

Von: luniki <notifications@github.com>
Gesendet: Dienstag, 25. Februar 2020 08:23
An: opencast/annotation-tool <annotation-tool@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [opencast/annotation-tool] Omit eye icon for "access" settings, becaus we us the eye icon differently now (hide annotations). Idea: (#341)


Public = Globe
Private = Lock or person-icon

**Comment by dagraf** [comment]
Looks fine on SWITCHcast-Staging. Thx!
