### ISSUE TITLE
Anchor of label annotations: When activated via single click they turn black

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#358]
At least the dot on the timeline should keep its colour.

**Comment by JulianKniephoff** [comment]
@dagraf That would then look something like this:

![image](https://user-images.githubusercontent.com/123272/86787291-3c0df900-c065-11ea-9261-2ec9abdf6293.png)

Would that be okay?

**Comment by dagraf** [comment]
Looks fine. Thx!

**Comment by dagraf** [comment]
Does only work when an active annotation was allready selected. When a non-selected annotations gets selected the dot still turns black.

**Comment by dagraf** [comment]
Why did you move this bug to backlog?

**Comment by JulianKniephoff** [comment]
Good question. :confused: Maybe by accident while dragging it to "Next". Will look into it.

**Comment by JulianKniephoff** [comment]
OOH no, it was because you reopened it:

![image](https://user-images.githubusercontent.com/123272/90772336-d1530d00-e2f4-11ea-958a-693924067a7d.png)

**Comment by dagraf** [comment]
Works fine, thx!
