### ISSUE TITLE
Vertical spacing between annotations is too large 

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#360]
Thanks for adding additional space between the top annotation and the timeline and between annotations itself. But you slightly overshot with the new spaces. Please reduce the spaces as following:
- between annotations: return to the old spacing
- between top annotation and the timeline: reduce the spacing to somewhat what is between the new and the old spacing (see screenshot: old spacing on the left).

Thx!

**Comment by JulianKniephoff** [comment]
What screenshot, though? :wink:

**Comment by dagraf** [comment]
<img width="1072" alt="Bildschirmfoto 2020-03-05 um 09 07 25" src="https://user-images.githubusercontent.com/15246287/75961361-2673a180-5ec2-11ea-8297-cc6d43e9e2ff.png">
This one! :)

**Comment by JulianKniephoff** [comment]
@dagraf directly in the middle between the old spacing would be this:

![image](https://user-images.githubusercontent.com/123272/86784600-fef43780-c061-11ea-8e4f-46d05b9c8ccb.png)

**Comment by dagraf** [comment]
Looks fine. Thx!
