### ISSUE TITLE
Enable multi content annotations

### ISSUE THREAD

**Issue by ebbertd** [opencast/annotation-tool#370]
Currently annotations can only have one type of content (free text, category label or category label including a scale) at one point of time.
This leads to users creating multiple annotations at the exact same point of time, but with different content.

Instead users should be able to create an annotations without having to determine the content beforehand. Only once the annotations has been created the user should be prompted to specify the content. At this point the user should be able to create one or multiple (not necessarily different) types of content as part of the annotation. 

In the annotations list these annotations should be expandable. By default all content should be collapsed and upon click users can view each content part.

![Annotationsliste](https://user-images.githubusercontent.com/20522234/80581349-51372d80-8a0d-11ea-8256-a16a6444dc1e.jpg)

**Comment by luniki** [comment]
Currently there are two ways to create an annotation:

a.) Press "Erstellen" to add a freetext annotation.
b.) Click on a "Kennzeichen" or an associated scale item to add a categorical annotation.

According to this issue annotations should be created in another way. Which is it?

**Comment by ebbertd** [comment]
Neiter, these two ways should be unified into one. User should be able to create an annotation and only afterwards choose what should be part of the annotation, freetext, categrical annotation or multiple entries of these.

**Comment by luniki** [comment]
My question was unclear: The current two ways will be replaced by a new one. Please describe what the user has to do to add a new annotation!

**Comment by ebbertd** [comment]
Oh, sorry. Now I understand your question and have to expand my answer as it can be misunderstood.

A new option to add a multi content annotation should be added. Upon clicking this button a popup should be opened in which the user can select with which content to fill this annotation.

However, so as not to confuse existing users of the tool the current two ways of creating annotations should be preserved. So user can still create free text annotations or categorical annotations as they are used to. The big difference needs to be that these are just shortcuts for creating a multi content annotation that is automatically filled with the single content (free text or categorical) selected.
This way experienced users can still use the tool as they are used to but it is possible to edit annotations that were added this way to add other content.

I hope that answers your question.

**Comment by luniki** [comment]
Please define the visual presentation of a collapsed annotation in the list of annotations. Currently we have this:

![image](https://user-images.githubusercontent.com/2993/81523030-e52dc100-934c-11ea-8b8b-2247ba27c458.png)

There are three annotations: freetext, scaling and label.

But how are mixed annotations handled? What about annotations containing multiple freetext-type items? What about annotations containing 20 labels?

**Comment by luniki** [comment]
One other question: Where should the button to create an empty annotation be placed?

**Comment by luniki** [comment]
And one another question: There are several UI glitches when editing an annotation as of now. How do you feel about a modal dialogs:
* The user intents to edit an exisiting annotation.
* Therefore they click on the edit icon :pen:
* A modal dialog pops up allowing the user to edit the selcted annotate.

**Comment by luniki** [comment]
One more question:

>Only once the annotations has been created the user should be prompted to specify the content.

So, the user clicks on a button. A new annotation is created. Is the user now prompted directly to specify the content? Or is this triggered after a user interaction?

**Comment by ebbertd** [comment]
> And one another question: There are several UI glitches when editing an annotation as of now. How do you feel about a modal dialogs:
> 
>     * The user intents to edit an exisiting annotation.
> 
>     * Therefore they click on the edit icon pen
> 
>     * A modal dialog pops up allowing the user to edit the selcted annotate.

That is a good idea which should make editing annotation easier.

**Comment by ebbertd** [comment]
> One more question:
> 
> > Only once the annotations has been created the user should be prompted to specify the content.
> 
> So, the user clicks on a button. A new annotation is created. Is the user now prompted directly to specify the content? Or is this triggered after a user interaction?

The user should be directly prompted to specify the content.

**Comment by ebbertd** [comment]
> One other question: Where should the button to create an empty annotation be placed?

Within the same area as the free text and categorical annotation. I suggest either under or above.

**Comment by ebbertd** [comment]
> Please define the visual presentation of a collapsed annotation in the list of annotations. Currently we have this:
> 
> ![image](https://user-images.githubusercontent.com/2993/81523030-e52dc100-934c-11ea-8b8b-2247ba27c458.png)
> 
> There are three annotations: freetext, scaling and label.
> 
> But how are mixed annotations handled? What about annotations containing multiple freetext-type items? What about annotations containing 20 labels?

Is a row of symbols feasible? So for example one symbol for free text followed by the short code for a label or a scale.

**Comment by dagraf** [comment]
> > Please define the visual presentation of a collapsed annotation in the list of annotations. Currently we have this:
> > ![image](https://user-images.githubusercontent.com/2993/81523030-e52dc100-934c-11ea-8b8b-2247ba27c458.png)
> > There are three annotations: freetext, scaling and label.
> > But how are mixed annotations handled? What about annotations containing multiple freetext-type items? What about annotations containing 20 labels?
> 
> Is a row of symbols feasible? So for example one symbol for free text followed by the short code for a label or a scale.

What about giving such multi content annotations a fixed color (all white?) which can not be used for categories? The collapsed annotation could then show for example the first annotation, be it text, scaling or label.

**Comment by dagraf** [comment]
> > One other question: Where should the button to create an empty annotation be placed?
> 
> Within the same area as the free text and categorical annotation. I suggest either under or above.

I suggest under free text and categorial annotations. As we have then some logic: the lowest opportunity to annotate gives the possibility to combine the to types above.

**Comment by ebbertd** [comment]
> > > One other question: Where should the button to create an empty annotation be placed?
> > 
> > 
> > Within the same area as the free text and categorical annotation. I suggest either under or above.
> 
> I suggest under free text and categorial annotations. As we have then some logic: the lowest opportunity to annotate gives the possibility to combine the to types above.

I agree, this makes sense.

**Comment by ebbertd** [comment]
> > > Please define the visual presentation of a collapsed annotation in the list of annotations. Currently we have this:
> > > ![image](https://user-images.githubusercontent.com/2993/81523030-e52dc100-934c-11ea-8b8b-2247ba27c458.png)
> > > There are three annotations: freetext, scaling and label.
> > > But how are mixed annotations handled? What about annotations containing multiple freetext-type items? What about annotations containing 20 labels?
> > 
> > 
> > Is a row of symbols feasible? So for example one symbol for free text followed by the short code for a label or a scale.
> 
> What about giving such multi content annotations a fixed color (all white?) which can not be used for categories? The collapsed annotation could then show for example the first annotation, be it text, scaling or label.

Thank you for the suggestion, I like it as it makes spotting these annotations in the list easier.
