### ISSUE TITLE
Better highlighting of active annotations

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#40]
Originally reported by: **Julian Kniephoff (Bitbucket: [JulianKniephoff](https://bitbucket.org/JulianKniephoff), GitHub: [JulianKniephoff](https://github.com/JulianKniephoff))**

----------------------------------------

In the context of pull request #14, @rrolf raised the issue that the highlighting of the active annotation(s) by a small red border is maybe not distinguished enough.

I would add that we might need to differentiate the highlighting a bit more, because annotations might be "active" for different reasons in different contexts (selecting it, the play head reaching its start time, commenting, ...).

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/40

**Comment by ebbertd** [comment]
The active annotation now has some shading and is easily distinguishable from the rest.
