### ISSUE TITLE
Double clickin on a annotation in the list does not always select and activate the correct answer

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#409]
The bug appears when I double click on annotation in the list that is at the top or bottom of the momentarily shown part of the list (see screencast: https://tube.switch.ch/videos/d37db386). I guess this is the reason why the bug appears:
1. When clicking once on a annotation in the list that is next to the top or bottom there is an automatic scroll happening to show it in the centre of the list.
2. When I double click on such an annotation the first click leads to an automatic scroll which then leads to the second (immediately following) click hitting a different annotation.
> Result: the wrong annotation gets activated and selected.

**Comment by dagraf** [comment]
Bug still exsits on cast-test.switch.ch

**Comment by JulianKniephoff** [comment]
@dagraf because it is not deployed, yet. :wink: Things got in the way yesterday, but I will do another deployment some time today.

**Comment by JulianKniephoff** [comment]
This should be taken care of, now.
