### ISSUE TITLE
Edit/Creat cateogries: Title is almost not readable

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#412]
When I edit or create an edit the written text in the title-textbox ist in light-grey on a white background (see screenshot: "Testkategorie" und "ABC"))
<img width="571" alt="Bildschirmfoto 2020-09-03 um 11 33 12" src="https://user-images.githubusercontent.com/15246287/92098531-a7f8ad80-edd9-11ea-8a19-3a693403139a.png">
. Therefore it is almost not visible what a admin is writing. 

Solution: Please change the colour to black. Thx!

**Comment by JulianKniephoff** [comment]
This is fixed in 12cb02fa89c845d7882ea2979c603d52dfdb755f.

@dagraf this is a tiny change; I will deploy it on SWITCHcast ASAP.

**Comment by dagraf** [comment]
Perfect. Thx!

**Comment by dagraf** [comment]
Perfect. Thx!
