### ISSUE TITLE
Bern Features: Shared categories do appear in the tab "All" even if I have no foreign track selected

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#417]
If I have no foreign track selected (for example when I open a video in the annotation tool for the first time) in the tab "All" all categories of other users, which have sharing options that allow me to see them, are visible (but greyed out). This should not be the case.

Solution: Categories which I theoretically can see should only be shown if I actually select the corresping track of a foreign user.

**Comment by Arnei** [comment]
This should be fixed by commit 59259a9bcab24b07cbb377588e4abf9c8cf1c770  in PR #407

**Comment by dagraf** [comment]
Looks fine and can be closed.
