### ISSUE TITLE
Bern Features: Category annotations do not show up in the list auf annotations

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#418]
They show up in the track, but not the list. When I try to reload the page, the tool does not oben at all (see screenshot). 

![grafik](https://user-images.githubusercontent.com/15246287/97587470-b63f0080-19fb-11eb-8a22-c7e8f1e87c25.png)

**Comment by dagraf** [comment]
Have you seen this issue? It does still appear.

**Comment by JulianKniephoff** [comment]
This was indeed an issue with the SWITCHcast fork. I can't point to any commit in this repo, but it should be fixed on their side now.

**Comment by dagraf** [comment]
Looks fine and can be closed.

**Comment by dagraf** [comment]
Fixed.
