### ISSUE TITLE
Bern features: Icons to switch between category affiliation is invisible

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#421]
There is a clickable box next to the trash bin but the chosen icons are invisible (see screenshot).
![Bildschirmfoto 2020-12-08 um 15 28 57](https://user-images.githubusercontent.com/15246287/101496778-778d5600-396a-11eb-93bc-cc22257f6a9a.png)

**Comment by Arnei** [comment]
Well this is embarrassing, I forgot to commit the image files. 

I now added the missing files to the PR, but they'll probably not be available on your test system until tomorrow, so here is at least a screenshot of how it should look like:
![Bildschirmfoto vom 2020-12-08 16-45-06](https://user-images.githubusercontent.com/14070005/101505928-246cd080-3975-11eb-9a89-9b864a84a727.png)

**Comment by dagraf** [comment]
Looks nice. Would it be possible to insert some free space between the new icons and the square to change the colour?

**Comment by dagraf** [comment]
Looks fine and can be closed. Thx!
