### ISSUE TITLE
Bern features: Labels of a category belonging to a series can only be edited in the video where it was created

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#422]
When I create a category that belongs to a series in video A and then edit this category in video B, changes in the title of the category do appear in video A (of course after a refresh/reload). Which is fine. 
But when I change labels, these changes only get saved temporarily and locally. When I reload the page after having made changes in video B, the changes are lost and the labels are the same as before. Also the changes do not get transferred to video A.

All changes that I make in video A get transferred to video B.

Solution: Please make sure that all changes to category titles and labels are always saved permanently and do alsways get transferred to the other videos of the same series.

**Comment by Arnei** [comment]
Good catch, thanks. 

With the most recent commit fe10fe1 to the PR #414, all changes to labels made on video B should now persist and transferred to other videos of the same series. 

Have you found anything else that does not get transferred besides from video B to other videos besides the labels (and of course scales, as we are currently not allowing scales on series categories)? For example category name or color.

**Comment by dagraf** [comment]
Changes of category name and color do get transferred. Everything what I do with labels does NOT get transferred: Edit label name, add label, remove label

**Comment by dagraf** [comment]
Looks fine and can be closed. Thx!
