### ISSUE TITLE
Bern features: Changing affiliation form "Belongs to a series" to "Belongs to this video" does not work

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#424]
When I change the affiliation of a category from "Belongs to a series" to "Belongs to this video" the category and its labels are still shown and can be selected in all other videos of this series. Of course I did a browser reload inbetween. The change the other way around (belongs to video > belongs to series) does work. 

Solution: When a user/admin changes the affiliation of a category form "Belongs to a series" to "Belongs to this video" the chosen category should only be offered in the video where this change was made (regardless of which video the category was created in). In all other videos the category, that now only belongs to a certain video, should disappear.

**Comment by Arnei** [comment]
To reiterate, what currently happens (or should happen at least) when a category is changed back to "Belongs to this video" from "Belongs to a series", this happens on all videos the category ever existed on. For example, if the category is changed back to a video category on video A, it will also do so video B.

This is currently intended behaviour, to avoid a user unexpectedly deleting categories from other videos where those categories are maybe still in use. Your solution would also be valid behaviour though. I simply do not know enough about the intended use cases of the feature to make an educated decision on how the feature should behave in this case. If you are sure that your solution is the intended way of how this should work, we can implement that.

In that case it might be a good idea to display a modal with a warning message, i.e. something like "Changing the affiliation of this category from series back to video will delete the category from all other videos of this series!".

**Comment by dagraf** [comment]
Thx for your explanation. I like your idea to display a modal with a warning message. Also the warning message seems appropriate. I am pretty sure that we should implement my solution, although I do not know all usecases of this feature. But I want to prevent the case, that someone does switch a category to belonging to a series by mistake and after having changed it back is forced to delete all unwanted "copies" in the other videos. Does that sound reasonable to you?

**Comment by Arnei** [comment]
I agree with you, having to delete a bunch of accidentally created categories on different videos would be very bothersome. Therefore I will try and implement your suggested solution, along with the warning modal I mentioned to avoid accidental deletion on the users part.

**Comment by Arnei** [comment]
Solved with commit https://github.com/opencast/annotation-tool/pull/414/commits/614c0136e91f4ef861bf63a604f8408f10aade58 and https://github.com/opencast/annotation-tool/pull/414/commits/d3187a5815ef7027ebe89d4268010f7f3055b168.

**Comment by dagraf** [comment]
Please alter german warning message.
Title: "Achtung: In Video-Kategorie ändern"
Text: "Wenn Sie die Zugehörigkeit dieser Kategorie von "gehört zur Serie" auf "gehört zum Video" ändern, wird die Kategorie in allen anderen Videos dieser Serie entfernt. Wollen Sie fortfahren?"
Button: "Ja, zu Video-Kategorie machen"

**Comment by dagraf** [comment]
Looks fine, thx!
