### ISSUE TITLE
Bern features: Tell users if the are deleting a category with video or series affiliation

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#426]
If a user/admin deletes a category belongig to a series, this category gets also deleted in all other videos. I would suggest to tell the user this fact in the modal which is shown when he clicks on the trash icon. It could say something like:

EN:
**Delete category**
This category belongs to a series and appears in all videos. If you delete this category, it will be deleted for all other videos as well. 
Do you really want to delete the "XYZ" category?

DE:
**Kategorie löschen**
Diese Kategorie gehört zur Serie und erscheint bei allen Videos. Wenn Sie diese Kategorie löschen, wird sie auch für alle anderen Videos gelöscht. 
Wollen Sie die Kategorie „XYZ“ wirklich löschen?

**Comment by Arnei** [comment]
Solved in commit https://github.com/opencast/annotation-tool/pull/414/commits/231c83a4a17dbdc7e83078348474268676cf9db3

**Comment by dagraf** [comment]
Looks fine, thx!
