### ISSUE TITLE
Installation instructions not working for v8

### ISSUE THREAD

**Issue by hpawe01** [opencast/annotation-tool#433]
I want to use docker for setting up an opencast instance with the annotation tool running following [installation instructions](https://github.com/opencast/annotation-tool/blob/master/documentation/opencast-installation.md).

I thought I could just use the `allinone` [Dockerfile](https://github.com/opencast/opencast-docker/blob/master/Dockerfiles/allinone/Dockerfile) and add the relevant build instructions from the documentation  (see https://github.com/opencast/opencast-docker/issues/150 for my initial question).

Unfortunately it is not working and I encountered multiple difficulties. I document them here for others and maybe someone can help me in the last step to make it work:

1. First I used the current opencast-docker version branch (9.1) and added some build instructions for the annotation-tool in the `build`-image of the `allinone` Dockerfile:
```Dockerfile
...
# Already existing build instruction for opencast
RUN git clone --recursive "${OPENCAST_REPO}" "${OPENCAST_SRC}" \
 && cd "${OPENCAST_SRC}" \
 && git checkout "${OPENCAST_BRANCH}" \
 && mvn --batch-mode install \
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
      -DskipTests=true \
      -Dcheckstyle.skip=true \
      -DskipJasmineTests=true \
 && tar -xzf build/opencast-dist-${OPENCAST_DISTRIBUTION}-*.tar.gz --strip 1 -C "${OPENCAST_HOME}"

# Build instructions for the annotation tool that I added
RUN git clone --recursive "https://github.com/opencast/annotation-tool.git" "${OPENCAST_ANNOTATION_TOOL_SRC}"
RUN cd "${OPENCAST_ANNOTATION_TOOL_SRC}" \
 && git checkout master \
 && mvn --batch-mode install \
      -DdeployTo="${OPENCAST_HOME}"

# This is that last line from the opencast build step. I extracted it to use the cache for building the annotation tool
RUN rm -rf "${OPENCAST_SRC}"/* ~/.m2 ~/.npm ~/.node-gyp
...
```
The build failed, because that annotation tool imports `org.opencastproject.util.data.functions.Tuples` in one of its [files](https://github.com/opencast/annotation-tool/blob/master/opencast-backend/annotation-impl/src/main/java/org/opencast/annotation/impl/persistence/ExtendedAnnotationServiceJpaImpl.java) but since v9 this file does not exists anymore in opencast ([v8.10](https://github.com/opencast/opencast/tree/8.10/modules/common/src/main/java/org/opencastproject/util/data/functions) vs [v9.1](https://github.com/opencast/opencast/tree/9.1/modules/common/src/main/java/org/opencastproject/util/data/functions)).

2. Then I tried to use the v8.10 of opencast for building the annotation tool by adding `-Dopencast.version=8.10` to the `mvn install` command. The build succeed but the initialization during the start of opencast failed. And http://localhost:8080/annotation-tool/index.html returned a `404` error.

3. Then I used the v8.10 branch opencast-docker `allinone` Dockerfile and did the same modifications as described in 1. and 2.
The build succeed but now it complained about the wrong version of the org.opencastproject.mediapackage dependency:
```
opencast_1  | 2021-01-08T21:31:41,054 | WARN  | (PaxLoggingServiceImpl$1ManagedPaxLoggingService:398) - Error while starting bundle: file:/opencast/deploy/annotation-tool-api-0-SNAPSHOT.jar
opencast_1  | org.osgi.framework.BundleException: Unable to resolve annotation-tool-api [10](R 10.0): missing requirement [annotation-tool-api [10](R 10.0)] osgi.wiring.package; (&(osgi.wiring.package=org.opencastproject.mediapackage)(version>=8.10.0)) Unresolved requirements: [[annotation-tool-api [10](R 10.0)] osgi.wiring.package; (&(osgi.wiring.package=org.opencastproject.mediapackage)(version>=8.10.0))]
```
If I omit the `-Dopencast.version=8.10` parameter I get the same error as described in 1.

Is the building and installation instruction outdated? And what do I have to do, to make it at least build and start?

Thanks in advance for any help!

**Comment by JulianKniephoff** [comment]
The installation instructions are indeed not up to date and/or complete. Unfortunately. However, you arrived at a combination that **should** work in theory. Can you verify that the bundle in question is really there?

Alternatively, you could also try a slightly earlier versions. I'm not sure I tested with 8.10, yet. :thinking:

**Comment by hpawe01** [comment]
Thank you for your feedback.

I will test it with 8.4 or which opencast version do you recommend?

Shouldn't the bundle (`org.opencastproject.mediapackage`) be in the `~/.m2` directory after building the opencast version? But I will check this as well.

**Comment by JulianKniephoff** [comment]
The bundle Karaf uses should actually be in the hierarchy beneat `<oepncast_base_path>/system`.

However, what I meant was rather: Can you check whether Karaf actually exports that package. You can check that with something like

```
package:exports | grep mediapackage
```

on your Karaf console.

8.4 should work; I recently tried 8.6 as well, IIRC.

**Comment by hpawe01** [comment]
Thanks @JulianKniephoff, but the issue was with the loading order of the deploy files (https://github.com/opencast/opencast-docker/issues/150, https://github.com/opencast/annotation-tool/issues/226). So, the installation is working now for v8.10.

I will change the title, so that I can close this issue.

**Comment by JulianKniephoff** [comment]
Aah, right, that makes sense. >_<

Glad you got it working. :D
