### ISSUE TITLE
Bern features: Changing series category title can create fake duplicates

### ISSUE THREAD

**Issue by Arnei** [opencast/annotation-tool#438]
Steps to repoduce:
1. Create a series category on video A
2. Change the title of the series category on video B (meaning any other video from the one the series category was originally created on)
3. Refresh the page with video B
4. You now have the category with the changed title, as well as a category with the unchanged title.

Deleting the duplicate will delete all copies of the category on all videos. 

How it looks:
![Bildschirmfoto vom 2021-01-12 17-12-33](https://user-images.githubusercontent.com/14070005/104344168-1aeb0100-54fd-11eb-84bc-7b6b6dda7d60.png)
(Where "Will it blend" is the series category after the title change, and "Will it blend???" the duplicate.

**Comment by Arnei** [comment]
Solved in PR #414 with commit 4e0b7fd837689eea82b1d086f21162c242163d06

**Comment by dagraf** [comment]
Looks fine and can be closed.
