### ISSUE TITLE
Bern features: Export > Annotations of categories "belonging to a series" do not exported all the time

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#451]
Annotations of categories "belongig to a series" get only supported in the one video, where this category got created.

Steps to reproduce:
- Have 2 videos in the same series (A and B).
- Create a category "belongig to a series" in video A.
- Make annotations with this category in video A and B.
- Export the annotations in both videos.
- Annotations made with this category are only shown in the export of the video A (where this category got created) but not in the export of video B (where the category is only shown, because it is a category "belongig to a series".

**Comment by Arnei** [comment]
I updated the PR with a solution and will pester Julian to deploy it to your testing system.

**Comment by dagraf** [comment]
Bug seems to have been fixed. Therefore I close it.
