### ISSUE TITLE
Search service doesn't know how to handle action: annotate-admin

### ISSUE THREAD

**Issue by felix-itz** [opencast/annotation-tool#453]
When publishing a MP to Engange with the `annotate(-admin)?` action, the search service complains that it does not know how to handle said action.

Here is how to reproduce:

1. Create a recording and publish it to Engage
2. Install Annotation Tool
3. Add annotate and annotate-admin actions for some roles in Opencast's AdminUI and republish the meta data
4. Look into the presentation/ engage logs:

```
| INFO  | (SearchServiceImpl:371) - Added mediapackage `cf48b9b2-de9e-4b00-a619-XXXX` to the search index, using ACL `[ROLE_ADMIN is allowed to read, ROLE_ADMIN is allowed to write, ROLE_ADMIN is allowed to annotate-admin, ROLE_ADMIN is allowed to annotate, 3a986c98382611d36d8427e4c0c0XXXX_Instructor is allowed to read, 3a986c98382611d36d8427e4c0c0XXXX_Instructor is allowed to write, 3a986c98382611d36d8427e4c0c0XXXX_Instructor is allowed to annotate, 3a986c98382611d36d8427e4c0c0XXXX_Learner is allowed to read, 3a986c98382611d36d8427e4c0c0XXXX_Learner is allowed to annotate]`
| WARN  | (SolrIndexManager:666) - Search service doesn't know how to handle action: annotate-admin
| WARN  | (SolrIndexManager:666) - Search service doesn't know how to handle action: annotate
```

Actual: Warnings in Logs

Expected: No warnings in Logs

----

The Annotation Tool and Engage appear to work as expected otherwise.

**Comment by JulianKniephoff** [comment]
Seeing as the Search Service/Engage is part of Opencast, not the Annotation Tool, I don't think there is anything I can do about it as part of this project. Sorry. :frowning_face:
