### ISSUE TITLE
Annotation tool does not load all the time

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#498]
I did try with newly uploaded (series: Annotation Tool: Test 2021Mai, Annotation-Tool: 2021Mai DGRTEST) and older videos (series: «Kommunikationstrainigs TESTS IML») but I have not found any rule. Here is what I observed:
- All newly uploaded videos do only load with a particular user but not with others (see first screenshot).
- Other videos (only older videos) do load with all users. 
- Some older video do not load at all (see second screnshot).

![Bildschirmfoto 2021-05-20 um 17 25 34](https://user-images.githubusercontent.com/15246287/119006879-0a5a0400-b991-11eb-9401-12252b44b681.png)

<img width="1261" alt="Bildschirmfoto 2021-05-20 um 17 33 20" src="https://user-images.githubusercontent.com/15246287/119007469-8b190000-b991-11eb-91b2-2cd1a1522ef4.png">

**Comment by dagraf** [comment]
For the new videos: It seems to me, that the first user who does ever open a video in the annotation tool can open it and all others don't. As if this user gets noted as "annotation owner"...

**Comment by Arnei** [comment]
This should already be fixed with the patch https://github.com/opencast/annotation-tool/pull/496, which might not be live on your system yet.

**Comment by JulianKniephoff** [comment]
Yeah, I think so, too. Should land on staging with the next deployment. I hope to get to that today or tomorrow. :)

**Comment by JulianKniephoff** [comment]
OK it should be up now. Can you check again, @dagraf? It works for me now.

**Comment by dagraf** [comment]
Yes, it works now for newly uploaded videos. All videos I have uploaded 20th May show the same bug. I guess this is because of the former bug and therefore I delete theses videos.

**Comment by JulianKniephoff** [comment]
@dagraf yes exactly, unfortunately the fix is only for newly annotated videos. :slightly_frowning_face:
