### ISSUE TITLE
How to add an icon in the admin-ng UI

### ISSUE THREAD

**Issue by fishfree** [opencast/annotation-tool#512]
That will be much easier to use.

**Comment by JulianKniephoff** [comment]
Sorry, but I'm confused. Is this a question about how to add an icon? Or a request for me to do it? And add it where? What icon are we talking about? :thinking:

**Comment by fishfree** [comment]
@JulianKniephoff Sorry for my fault. I find the title of the issue isn't complete. I mean how to add an icon in the admin-ng UI as the screenshot below:
![image](https://user-images.githubusercontent.com/1741341/133171608-cb745fb8-1a58-4a85-9a6e-a4ad8088f0a0.png)

BTW: It will be much better also providing a icon linked to an annotation portal like the media module:
![image](https://user-images.githubusercontent.com/1741341/133171928-d885f17b-88cf-4a13-8106-ddafa0c7fd03.png)

**Comment by JulianKniephoff** [comment]
This is unfortunately not something we can resolve within the scope of this project. It's something the folks over at https://github.com/opencast/opencast need to take care of.

I'll close this issue, but don't feel discouraged. You could create an issue there, or ask in [Matrix](https://docs.opencast.org/#matrix-room-chat) or on the [mailing lists](https://docs.opencast.org/#mailing-lists) if you want to do it yourself but don't know how. This issue tracker just isn't the right place for it.

As a simpler alternative to implementing such an icon in the Opencast Admin UI; You can define your own publication channel as described [here](https://docs.opencast.org/develop/admin/#workflowoperationhandlers/publish-configure-woh/#publication-channel-labels-and-icons). This would add a link to the publications popover in the events table, for which you can configure the title and (optionally) an icon. In practice, this could look like this.

![Selection_094](https://user-images.githubusercontent.com/123272/133252356-08eea3e4-feb1-48e7-8815-b5712acefb29.png)

(Ignore the SWITCH branding. "SWITCHcast annotate!" is SWITCH's brand name for the Annotation Tool, and that link could just as well say "Opencast Annotation Tool" or "Bananarama".)

**Comment by fishfree** [comment]
@JulianKniephoff In fact, I tried your method. But in Opencast 10.2, there is no files named etc/listproviders/publication.channel.labels.properties either etc/listproviders/publication.channel.icons.properties, only a etc/listproviders/publication.channels.properties, I appended `annotation={"label":"Annotation Tool", "icon":"img/engage_2x.png", "order":5}`, but still no popup annotation-tool icons shows up.

**Comment by JulianKniephoff** [comment]
You also need to actually publish to that channel in your workflow using something like this:

```xml
<operation
  id="publish-configure"
  exception-handler-workflow="partial-error"
  description="Publish to the Annotation Tool">
  <configurations>
    <configuration key="channel-id">annotation</configuration>
    <configuration key="url-pattern">https://whatever.com/annotation-tool/index.html?id=${event_id}</configuration>
  </configurations>
</operation>
```

See also https://docs.opencast.org/develop/admin/#workflowoperationhandlers/publish-configure-woh/.

**Comment by fishfree** [comment]
@JulianKniephoff Yes, of course I've added that operation handler into my workflow. And I can acess the annotation tool by https://whatever.com/annotation-tool/index.html?id=${event_id}

**Comment by JulianKniephoff** [comment]
That's weird. :thinking: With those two things it should be there. You might still want to ask on the mailing lists or in the community chat, because if this doesn't work, it's definitely an Opencast problem, and not specific to the Annotation Tool. (The tool is really not involved at all here.)

**Comment by fishfree** [comment]
> @JulianKniephoff In fact, I tried your method. But in Opencast 10.2, there is no files named etc/listproviders/publication.channel.labels.properties either etc/listproviders/publication.channel.icons.properties, only a etc/listproviders/publication.channels.properties, I appended `annotation={"label":"Annotation Tool", "icon":"img/engage_2x.png", "order":5}`, but still no popup annotation-tool icons shows up.

@JulianKniephoff Is the problem related to this change in the Opencast 10.2?

**Comment by JulianKniephoff** [comment]
You said you appended to `etc/listproviders/publication.channels.properties`, right? That should be correct.

**Comment by fishfree** [comment]
@JulianKniephoff Anyway, thank you very much!
