### ISSUE TITLE
Look of triangle to open category modal

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#520]
Please get rid of the "bordered button" (see screenshot) and make triangle slightly larger and completely in black (for greater contrast > see doc with specs). If a bordered button, then please center the triangle (vertically and horizontally).
![Bildschirmfoto 2021-10-06 um 21 00 07](https://user-images.githubusercontent.com/15246287/136266818-7dd3d207-fcf7-4696-b52a-9abf0aace097.png)

**Comment by JulianKniephoff** [comment]
Not quite done, yet, but at least the tabs should look better now:

![image](https://user-images.githubusercontent.com/123272/136809503-e261279e-a3fb-41af-84af-14d3c59001ff.png)

This is also already on staging. :smile:

**Comment by dagraf** [comment]
Looks better, indeed. But please move the triangles a little higher and make them still a little bigger.

**Comment by JulianKniephoff** [comment]
![image](https://user-images.githubusercontent.com/123272/140718889-e58f20c4-f502-4cb3-8b33-33869715811d.png)
 
Like this maybe? :thinking:

**Comment by JulianKniephoff** [comment]
![image](https://user-images.githubusercontent.com/123272/140723424-28ed6e08-6d2a-494b-82bc-69fcb9d5dd67.png)

And with the categories fixed as well.

**Comment by dagraf** [comment]
Perfect. Thx!

**Comment by dagraf** [comment]
Looks fine, thx!
