### ISSUE TITLE
In category modal: Position and heading of "Scale:"

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#523]
1. Place possibility to choose a scale at the very bottom of the modal (see doc with specs). Otherwise this will be misunderstood ("Do I have to select a scale now?").
2. Insert a heading: "Scale (optional)"

**Comment by JulianKniephoff** [comment]
@dagraf Something like this?

![image](https://user-images.githubusercontent.com/123272/140756054-56ea00fc-bdf7-4323-9cd9-5903cc1558aa.png)

That's more or less what the old scale modal had. The only way I can think of to *reliably* distinguish it from everything else (you can still name a scale "-- NO SCALE SELECTED --") is to actually mark all the others. So you would have something like

* No scale (or whatever formatting/wording we want)
* Scale: name of the scale

That way, even if you name a scale "No scale", it would show up as "Scale: No scale" in the list. It looks a bit weird, though, admittedly.

Thoughts? :thinking:

**Comment by dagraf** [comment]
It does not look that pretty but I can live with the solution "-. NO SCALE SELECTED --". And I don't think that any teacher would really try to name a scale "-- NO SCALE SELECTED --". :)

**Comment by dagraf** [comment]
Looks fine, thx.
