### ISSUE TITLE
In category modal: Alter wording "Etikette"

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#525]
Please write only "Label" oder "Label / Etikett" (see doc with specs).

**Comment by JulianKniephoff** [comment]
For reference:

![image](https://user-images.githubusercontent.com/123272/136768541-c45c4ce5-29bc-423a-ac95-9d8d4a43646d.png)

Are you talking about the header only? I realize the headers don't exist in the spec, but I thought some separation between the different fields might be nice.

The spec put "Label / Etikett" on top of the label column. We just have Etikett now. We can change that of course, but consider that we might refer to labels in other places that are not expected by the spec as well. Right now for example we have the "add label" button (see also https://github.com/opencast/annotation-tool/issues/527#issuecomment-939863702). Should we use "Label / Etikett" everywhere? I think that's a bit unwieldy. :thinking: 

Also, a bit of a nitpick: Typographically it should probably rather be "Label/Etikett" without the spaces. :sweat_smile:

**Comment by dagraf** [comment]
After some feedback of the CH-Community: Please get rid of german "Etikette" and write "Label" instead. Thx!

**Comment by dagraf** [comment]
Looks fine, thx!
