### ISSUE TITLE
Category modal: Correct wording of information that categories belonging to a series can not have scales

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#529]
Jetzt: „Serienkategorien können keine Skalen haben“ > Spezifiziert und bitte so umsetzen: „Diese Kategorie gehört zu einer Serie. Daher kann ihr keine Skala zugeordnet werden.“

**Comment by JulianKniephoff** [comment]
I just deployed a change to staging. It looks like this now:

![image](https://user-images.githubusercontent.com/123272/136774199-0286af7e-bc23-439f-ba3e-0c2ed57c6dff.png)

![image](https://user-images.githubusercontent.com/123272/136774203-5a2e4484-7398-4874-af52-f35a6792289a.png)

Is this ok? Especially the text for the other conflict didn't find mention here, is it fine as it is?

**Comment by dagraf** [comment]
Looks fine, thx!
