### ISSUE TITLE
Sharing option of categories in tab mine: "Share with admin" does work but categories get also shown to users

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#550]
If a normal user/students chooses the category-sharing option "Shared with admin" the annotations made using this category get only shown to admins, which is fine. But: The category itself gets also shown to normal users. It appears in the new category tab which is named after this user that has shared its category and track. This should not be the case.

See screenshots:

User sharing his categories (Mit allen resp. Mit Admin):
![Screenshot (29)](https://user-images.githubusercontent.com/15246287/143019361-2fd5655e-35bb-4b22-a3d1-031b00e22f48.png)

View of admin, which is correct:
![Screenshot (30)](https://user-images.githubusercontent.com/15246287/143019364-9d261955-438d-4909-9fc3-929f33001880.png)

View of user > Category "Mit Admin" should not be shown here:
![Screenshot (31)](https://user-images.githubusercontent.com/15246287/143019365-3308a800-a699-4913-896d-ecd182d3f192.png)

**Comment by JulianKniephoff** [comment]
This seems to be true even for private categories. :thinking:

**Comment by dagraf** [comment]
True.

Note: It's not an urgent bug but should be fixed some time...

**Comment by dagraf** [comment]
Bug does not exist anymore in the merged version. Therefore I close this issue.
