### ISSUE TITLE
Public category with access private still shows on other videos

### ISSUE THREAD

**Issue by Arnei** [opencast/annotation-tool#553]
I'm not sure why you can even set the access on public categories (shouldn't they always be public?), but if you set a public category to private, it will still show for other users. BUT the annotations created from that category will not show for other users. Annotations created by other users with this category will show until reload.

**Comment by Arnei** [comment]
This will be closed with #547, where setting the access for public categories is not possible anymore

**Comment by JulianKniephoff** [comment]
This has happened by now, so closing. :slightly_smiling_face:
