### ISSUE TITLE
Public tracks of other users are shown automatically when a user first starts to annotate a video

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#573]

**Comment by dagraf** [comment]
This bug appears again in the merged version. Steps to reproduce it:

- In a series there is at least one video. In this video, a user A has created at least one annotation and set his track to "Shared with all".
- User B opens this video in the annotation tool.
- User A's track is automatically displayed to User B. > that is the error.
- User B reloads the browser.
- User A's track is no longer displayed automatically, but can be shown via "Manage tracks". > This is the desired behavior.

Translated with www.DeepL.com/Translator (free version)

**Comment by dagraf** [comment]
It now works as expected. Thx for the fix!
