### ISSUE TITLE
Demo link on github doc broken

### ISSUE THREAD

**Issue by cgruber-uos** [opencast/annotation-tool#582]
On the documentation page at https://github.com/opencast/annotation-tool/blob/master/documentation/Overview.md you can find a demo link to https://entwinemedia.github.com/annotations/ what is broken / 404. 

Would be great to have a working demonstration for the OC annotation tool to show (and perhaps test) the tool, simmilar to develop.opencast.org/

**Comment by dagraf** [comment]
@cgruber-uos If you would like to test the annotation tool we are running at the University of Bern, please contact me (david.graf@unibe.ch). I could provide you with a test account. Feature wise we are similar to the version in the master branch.
