### ISSUE TITLE
How to use structured annotations?

### ISSUE THREAD

**Issue by fishfree** [opencast/annotation-tool#586]
There is no such documentation. I tried created some scales and categories, but couldn't figure out how to use them, how to insert. I guess scales are something like controlled vocabularies? Am I right?

**Comment by dagraf** [comment]
When using structured annotations you mainly work with categories and their labels. Scales are only there to specify a chosen label even further. Find attached our manual (in german, structured categories on page 8): https://ilias.unibe.ch/goto_ilias3_unibe_file_937701_download.html

**Comment by JulianKniephoff** [comment]
@dagraf thx for that link!

@fishfree documentation is unfortunately a bit lacking in this project, not only the user-facing aspect. I just created #587 to track this. In general, though, I would say that his kind of question rather belongs on the new mailing list that we have now: See [here](https://github.com/opencast/annotation-tool#communication). (One of the few parts of the docs that's actually pretty up-to-date. 😉

**Comment by fishfree** [comment]
@dagraf Thank you! I get some ideas of the structured annotations.
