### ISSUE TITLE
A category shared with "all users" can no longer be edited

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#596]
This bug appears only for student-users (ANNOTATE), it does not appear for admin-users (ANNOTATE, ANNOTATE-ADMIN):

A category shared with "all users" can no longer be edited by the user with the "ANNOTATE" right. As soon as a categories accessibility option is set tho "share with all users", the triangle with which the drop down menu can be opened gets not shown any more (see screenshot).

<img width="973" alt="Bildschirmfoto 2023-02-13 um 22 25 20" src="https://user-images.githubusercontent.com/15246287/218577950-73b650cc-3b4a-4820-8e6e-7f533196bb0d.png">

**Comment by oellers** [comment]
Thanks for pointing that out, we noticed this one as well. The behaviour should also exist in the current master/main; 

- Suggestion: We will change the behaviour so that non-admins can edit their own categories after sharing them publicly.

**Comment by dagraf** [comment]
Bug seems not to exist anymore. Therefore, I close this issue.
