### ISSUE TITLE
deployTo no longer works

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/annotation-tool#624]
Currently no bundles are created in the path `deployTo` points to. Looks like this was broken by https://github.com/opencast/annotation-tool/commit/4a2d8ee3d2f6913f226de1610c480d604fab2974 But it's not that easy to revert that commit and I can't figure out what is wrong with it.

**Comment by KatrinIhler** [comment]
Apparently you now need to use `deploy` instead of `install` and maybe the option ` -Dmaven.deploy.skip`. Also only the `features.xml` will be created.

**Comment by JulianKniephoff** [comment]
It works if you speak the proper incantations, which have changed (intentionally) in that commit. This just needs to be documented: #625.
