### ISSUE TITLE
Newly inserted annotations have no length in the timeline

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#631]
Branch: Stable

When I create a new annotation, it has no length in the timeline. Therefore, all newly inserted annotations can hardly be seen.

Note: When I transform a range-annotation (= an annotation with duration) to a point in time annotation it has some width and also the anchor. Maybe in this old issue could be some usefull information: https://github.com/opencast/annotation-tool/issues/299

See screenshot:
- Left: How it is in the stable branch.
- Right: How it should be = Give newly inserted annotations some width and add the anchor tho the timeline.

<img width="986" alt="Bildschirmfoto 2024-11-26 um 08 55 51" src="https://github.com/user-attachments/assets/ec2c5392-edd6-4e93-9333-ec77870f8dc3">

**Comment by jduehring** [comment]
@dagraf Please tell me if I am missing something, but would it be sufficient to just add every new annotation as a point in time annotation? As you said these already have a fixed width and anchor. Currently it seems that each new annotation gets a default length of 0.5 seconds which leads to the issue. 

We could set the default length of a new annotation to 0 (therefore beeing a point in time annotation) and then the user can convert it to a range annotation if needed, either by dragging the annotation or through the "edit" functionality. 

Also do we really want an anchor for range-annotations? At least for me it seems more intuitive to have them only for point-in-time annotations, when the width of the annotation does not accurately represent its actual length.

**Comment by dagraf** [comment]
@jduehring Thx for asking. Yes, please add every new annotation as a point in time annotation. 

No, we do not want an anchor for range-annotations.

**Comment by dagraf** [comment]
It now works as expected. Thx for the fix!
