### ISSUE TITLE
(free-text) annotations are moved together and not separately

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#66]
Originally reported by: **Thomas Schraml (Bitbucket: [TSchraml](https://bitbucket.org/TSchraml), GitHub: [TSchraml](https://github.com/TSchraml))**

----------------------------------------

I have the following setup: Two free-text annotations are created at the same point of the video (e.g. at 0 min, 0 sec). If I now want to move the first annotation with the cursor to another point of the video, with Firefox 57 this works as intended. With Chrome 62 the second annotation is moved to the same position as the first annotation (which only should be moved). In Firefox this also happens, when I want to move the second annotation e.g. from 0 min, 0 sec to 0 min, 10 sec and the first annotation is on a point between 0 and 10 sec
The problems happens with annotations with and without a length and also with more than 2 annotations: Every time two annotations are moved, but only one annotation should be moved.

The same problem occurs with category-annotations with Firefox as well as with Chrome.

The problem only affects the visualization in the track view. In the list right to the track view the information (position / point of the video) is changed as intended - and is displayed properly after loading the tool again.

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/66

**Comment by ebbertd** [comment]
This has been fixed with the new timeline.
