### ISSUE TITLE
Change color of free-text annotations

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#68]
Originally reported by: **Thomas Schraml (Bitbucket: [TSchraml](https://bitbucket.org/TSchraml), GitHub: [TSchraml](https://github.com/TSchraml))**

----------------------------------------

The color of a free-text annotation is the same as the color of an active track (picture). It would be better to use different colors for a better visualization.

![track.PNG](https://bitbucket.org/repo/7kKKrp/images/2310294621-track.PNG)

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/68

**Comment by ebbertd** [comment]
This has been solved. Free text annotations and the background now have a different color.
