### ISSUE TITLE
Length of annotations cannot be changed by cursor

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#69]
Originally reported by: **Thomas Schraml (Bitbucket: [TSchraml](https://bitbucket.org/TSchraml), GitHub: [TSchraml](https://github.com/TSchraml))**

----------------------------------------

When I add one or two annotations at the same point of the video, I can easily adjust the length of one annotation by cursor at the right end of the annotation. If I add another annotation at the same point like the two annotations before, I **can't** adjust die length this annotation anymore. It is only possible to edit the length of the first two annotations by cursor.

Another problem is that after changing the zoom level it is not possible to adjust the length of any annotation by cursor. The cursor doesn't change to adjust the length of the annotation. It is only possible to move the annotation to another point of the video. After moving the annotation, it is strangely possible to adjust the length. If I change the zoom level again, it is again impossible to adjust the length of an annotation by cursor. Only if I move the annotation at this zoom level again, I am able to adjust the length.
 
These problems occur with Firefox and Chrome on Windows 10 and MacOS 10.13.

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/69

**Comment by ebbertd** [comment]
I can no longer reproduce this bug.
