### ISSUE TITLE
Hotkeys for frequently used labels

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#7]
Originally reported by: **Rüdiger Rolf (Bitbucket: [rrolf](https://bitbucket.org/rrolf), GitHub: [rrolf](https://github.com/rrolf))**

----------------------------------------

Keyboard shortcuts could be used to set the start point for a label. A suggestion would be to use the 0-9 keys as a configureable shortcut for categories

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/7

---

Also maybe space for pausing the video.

**Comment by ebbertd** [comment]
Part of the keyboard shortcuts could be that it is possible to pause / play the video using _Space_ and to delete annotations using _Del_.

**Comment by JulianKniephoff** [comment]
Note that deleting annotations is already possible with the backspace key. I can of course trivially change that to `del` (or both), but could you, @ebbertd, confirm whether the functionality behind that key is enough? Because if not, this might be a bigger issue than we thought. :wink: (Deletion is handled very weirdly by the tooll ...)

**Comment by JulianKniephoff** [comment]
As for the label shortcuts: Can we spell out again how this is supposed to work, at least for this sprint? Which keys should be bound to what and how configurable should this all be?

**Comment by ebbertd** [comment]
Using backspace for deleting is fine.

As for the categories / labels. Would it be possible to number these? I mean to use a two digit hotkey in the format XY. X could correspond to the category and Y to the label. So 11 would be the first label in the first category and 58 would be the fifth category and the eighth label. This would allow nine categories with nine labels each to be accessed quickly.

**Comment by JulianKniephoff** [comment]
Ooh, as an old Vim (now Emacs + evil-mode) user, I like that idea very much! :smile:

**Comment by JulianKniephoff** [comment]
Next unforseen question: How does this interact with scale values? If the category has a scale, we also have to specify the scale value, when annotating using its labels.

**Comment by ebbertd** [comment]
Is adding a third digit too much? So if no scales exist XY would create the annotation and if scales exist XYZ would be needed?

**Comment by JulianKniephoff** [comment]
Yeah, that would be one way. We'll see how it turns out. :wink:
