### ISSUE TITLE
Fullscreen mode does not work properly

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#70]
Originally reported by: **Thomas Schraml (Bitbucket: [TSchraml](https://bitbucket.org/TSchraml), GitHub: [TSchraml](https://github.com/TSchraml))**

----------------------------------------

If I want to play a video in fullscreen mode, the video is not on the full screen (see screenshot).

![vollbild_klein.jpg](https://bitbucket.org/repo/7kKKrp/images/464933176-vollbild_klein.jpg)

----------------------------------------
- Bitbucket: https://bitbucket.org/opencast-community/annotation-tool/issue/70

**Comment by ebbertd** [comment]
This is fixed in the current 2.0 version. This issue can be closed.

**Comment by JulianKniephoff** [comment]
Cool! :smile:
