### ISSUE TITLE
Changing the color of a category is horribly broken

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#96]
After creating a new category with a label and setting its color, a newly created annotation with that label has the correct color. Changing the color of the category again and creating another annotation with the label gives this new annotation the correct color, but the color of the first annotation changes as well.

After a reload, though, the first annotation has its original color.  Changing the color of the category **now** has no effect on either new or old annotations with the label, i.e. old annotations keep their color and new ones also get the old color, as opposed to the new one.

After reloading again, any newly created annotations from the previous step, though, are in the default mud color!

---

**EDIT**: After some of the recent major refactorings, I now witness the following behavior: New labels (and their annotations) get the current color of the category; so far, so good. Changing the color also changes the labels, but not the annotations. Creating a new label after changing the color again behaves correctly. It seems like the color is saved with the annotations instead of just looked up at the labels.

**Comment by ebbertd** [comment]
In the current version changing color is easy, all labels of a category get changed directly and keep their color after a reload.
